# Generated by Django 4.2.3 on 2023-08-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="uploaded_pdfs/")),
                (
                    "deal_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash Deal"),
                            ("finance", "Finance Deal"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                    ),
                ),
                ("text_boxes", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
